#!/bin/sh
set -u
cd "$(dirname "$0")"

VENDOR=lge
DEVICE=batman_lgu
OUTDIR=vendor/$VENDOR/$DEVICE
MAKEFILE=../../../$OUTDIR/$DEVICE-vendor-blobs.mk
LINK_LIBRARIES="liboncrpc libnv libaudioalsa libacdbloader libacdbmapper libstlport libgps.utils libaudcal libdsm libqueue libdiag libgsl"

(cat << EOF) > $MAKEFILE
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Linkable prebuilts are declared in prebuilt-libraries.mk.
PRODUCT_PACKAGES += $LINK_LIBRARIES libpn544_fw

EOF

printf 'PRODUCT_COPY_FILES +=' >> "$MAKEFILE"
for ENTRY in `egrep -v '(^#|^$)' proprietary-files.txt`; do
  PATHS=${ENTRY%%|*}
  FILE=${PATHS%%:*}
  if [ "$FILE" = "lib/libtime_genoff.so" ] || \
     [ "$FILE" = "lib/egl/libEGL_adreno200.so" ] || \
     [ "$FILE" = "lib/egl/libGLESv2_adreno200.so" ]; then
    continue
  fi
  case "$FILE" in
    lib/liboncrpc.so|lib/libnv.so|lib/libaudioalsa.so|lib/libacdbloader.so|lib/libacdbmapper.so|lib/libstlport.so|lib/libgps.utils.so|lib/libaudcal.so|lib/libdsm.so|lib/libqueue.so|lib/libdiag.so|lib/libgsl.so|vendor/firmware/libpn544_fw.so)
      continue
      ;;
  esac
  DEST=$FILE
  case "$PATHS" in
    *:*) DEST=${PATHS#*:} ;;
  esac
  if [ "$FILE" = "lib/hw/sensors.msm8660.so" ] && [ "$DEST" = "$FILE" ]; then
    DEST=lib/hw/sensors.vendor.msm8660.so
  elif [ "$FILE" = "lib/hw/camera.msm8660.so" ] && [ "$DEST" = "$FILE" ]; then
    DEST=lib/hw/camera.vendor.msm8660.so
  fi
  printf ' \\\n  %s' "$OUTDIR/proprietary/$FILE:system/$DEST" >> "$MAKEFILE"
done
printf '\n' >> "$MAKEFILE"

(cat << EOF) > ../../../$OUTDIR/$DEVICE-vendor.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/$VENDOR/$DEVICE/overlay

\$(call inherit-product, vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk)
EOF

(cat << EOF) > ../../../$OUTDIR/BoardConfigVendor.mk
# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$VENDOR/$DEVICE/setup-makefiles.sh
EOF

# Keep the install paths used by the legacy blobs while providing real link
# dependencies to Kati/Ninja. Do not write directly into obj/lib.
PREBUILTS=../../../$OUTDIR/prebuilt-libraries.mk
cat > "$PREBUILTS" << EOF
# Generated by device/$VENDOR/$DEVICE/setup-makefiles.sh. Do not edit.
EOF
for LIBRARY in $LINK_LIBRARIES; do
  ENTRY=$(grep -E "^lib/$LIBRARY[.]so(:|[|]|$)" proprietary-files.txt)
  PATHS=${ENTRY%%|*}
  INSTALL_PATH='$(TARGET_OUT_SHARED_LIBRARIES)'
  if [ "${PATHS#*:}" = "vendor/lib/$LIBRARY.so" ]; then
    INSTALL_PATH='$(TARGET_OUT_VENDOR_SHARED_LIBRARIES)'
  fi
  SHARED_LIBRARIES=$(readelf -d "../../../$OUTDIR/proprietary/lib/$LIBRARY.so" 2>/dev/null | sed -n 's/.*(NEEDED).*\[\(.*\)\.so\].*/\1/p' | sed 's/^libc$/libc.bootstrap/' | tr '\n' ' ' | sed 's/ *$//')
  cat >> "$PREBUILTS" << EOF

include \$(CLEAR_VARS)
LOCAL_MODULE := $LIBRARY
LOCAL_MODULE_OWNER := $VENDOR
LOCAL_SRC_FILES := proprietary/lib/$LIBRARY.so
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
LOCAL_MODULE_TAGS := optional
LOCAL_MULTILIB := 32
LOCAL_STRIP_MODULE := false
LOCAL_MODULE_PATH := $INSTALL_PATH
LOCAL_CXX_STL := none
LOCAL_SHARED_LIBRARIES := $SHARED_LIBRARIES
EOF
  if [ "$LIBRARY" = "libstlport" ]; then
    cat >> "$PREBUILTS" << 'EOF'
LOCAL_NOTICE_FILE := $(LOCAL_PATH)/licenses/libstlport.txt
EOF
  fi
  echo 'include $(BUILD_PREBUILT)' >> "$PREBUILTS"
done
